[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g npm@9.8.1",
  "cd backend && npm install --legacy-peer-deps",
  "cd frontend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate && npm run build",
  "cd frontend && npm run build",
  "mkdir -p backend/dist/public && cp -r frontend/build/* backend/dist/public/"
]

[start]
cmd = "cd backend && npm run start"
